[package]
name = "minidox-redoxfs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "RedoxFS branching adapter for minidox"
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
minidox-cache.workspace = true
redoxfs.workspace = true
redox_syscall.workspace = true
serde.workspace = true

[dev-dependencies]
tempfile.workspace = true
